#!/usr/bin/env python3
"""Generate src/i18n/catalog.rs from the CanfarDesktop reference RESW files.

The Windows reference keeps its UI strings in Strings/{en-US,fr-FR}/Resources.resw
as a flat "x:Uid.Property" -> value model. This script normalizes those keys into
clean `Area_Name[_Suffix]` keys, verifies the EN and FR key sets are identical, and
emits a compile-time Rust catalog (two `&[(&str, &str)]` slices) that is embedded in
the binary — so no locale files ship in the .deb (matches the app's self-contained,
single-binary packaging).

Run:  python3 scripts/gen_i18n_catalog.py [path-to-CanfarDesktop]
"""
import sys
import os
import re
import xml.etree.ElementTree as ET

REF_DEFAULT = os.path.join(os.path.dirname(__file__), "..", "..", "CanfarDesktop")

# Property suffix -> clean key suffix ("" means it is the element's primary text).
PRIMARY = {"Content", "Text", "Header", "Title", "Subtitle", "Description"}
SUFFIX_MAP = {
    "ToolTipService.ToolTip": "Tooltip",
    "AutomationProperties.Name": "A11y",
    "AutomationProperties.HelpText": "A11yHelp",
    "PlaceholderText": "Placeholder",
    "CloseButtonText": "CloseButton",
    "PrimaryButtonText": "PrimaryButton",
    "SecondaryButtonText": "SecondaryButton",
    "OnContent": "On",
    "OffContent": "Off",
    "Message": "Message",
}

USING_RE = re.compile(r"\.\[using:[^\]]+\]")


def normalize(raw):
    """Map a raw RESW key to a clean Area_Name[_Suffix] key."""
    # Drop the "[using:Namespace]" attached-property escape.
    name = USING_RE.sub(".", raw)
    name = name.replace("..", ".")
    if "." not in name:
        return name  # plain Loc.T key, e.g. Common_Close
    base, prop = name.split(".", 1)
    if prop in PRIMARY:
        return base
    if prop in SUFFIX_MAP:
        return f"{base}_{SUFFIX_MAP[prop]}"
    # Unknown property: fold it into the key so nothing collides silently.
    return f"{base}_{prop.replace('.', '_')}"


def load(path):
    tree = ET.parse(path)
    root = tree.getroot()
    out = {}
    for data in root.findall("data"):
        raw = data.get("name")
        if raw is None:
            continue
        value_el = data.find("value")
        value = value_el.text if value_el is not None and value_el.text is not None else ""
        key = normalize(raw)
        if key in out and out[key] != value:
            # Collision between two distinct raw keys mapping to the same clean key.
            # Disambiguate by appending a short hash of the raw suffix.
            key = f"{key}_{abs(hash(raw)) % 1000}"
        out[key] = value
    return out


def rust_escape(s):
    r = []
    for ch in s:
        if ch == "\\":
            r.append("\\\\")
        elif ch == '"':
            r.append('\\"')
        elif ch == "\n":
            r.append("\\n")
        elif ch == "\r":
            r.append("\\r")
        elif ch == "\t":
            r.append("\\t")
        else:
            r.append(ch)  # keep literal UTF-8 (incl. é, U+00A0) byte-for-byte
    return "".join(r)


def main():
    ref = sys.argv[1] if len(sys.argv) > 1 else REF_DEFAULT
    en_path = os.path.join(ref, "Strings", "en-US", "Resources.resw")
    fr_path = os.path.join(ref, "Strings", "fr-FR", "Resources.resw")
    en = load(en_path)
    fr = load(fr_path)

    en_keys, fr_keys = set(en), set(fr)
    if en_keys != fr_keys:
        only_en = sorted(en_keys - fr_keys)
        only_fr = sorted(fr_keys - en_keys)
        sys.stderr.write(
            f"WARNING: EN/FR key sets differ. EN-only={only_en[:10]} FR-only={only_fr[:10]}\n"
        )
        # Fill missing FR keys with the EN value so the tables stay aligned.
        for k in only_en:
            fr[k] = en[k]
        for k in only_fr:
            en[k] = fr[k]

    keys = sorted(set(en) | set(fr))
    out = os.path.join(os.path.dirname(__file__), "..", "src", "i18n", "catalog.rs")
    with open(out, "w", encoding="utf-8") as f:
        f.write("// @generated by scripts/gen_i18n_catalog.py — DO NOT EDIT BY HAND.\n")
        f.write("// Source: CanfarDesktop/Strings/{en-US,fr-FR}/Resources.resw\n")
        f.write(f"// {len(keys)} keys. Regenerate after translation updates.\n\n")
        f.write("#[rustfmt::skip]\n")
        f.write("pub static EN: &[(&str, &str)] = &[\n")
        for k in keys:
            f.write(f'    ("{rust_escape(k)}", "{rust_escape(en[k])}"),\n')
        f.write("];\n\n")
        f.write("#[rustfmt::skip]\n")
        f.write("pub static FR: &[(&str, &str)] = &[\n")
        for k in keys:
            f.write(f'    ("{rust_escape(k)}", "{rust_escape(fr[k])}"),\n')
        f.write("];\n")
    print(f"Wrote {out}: {len(keys)} keys (EN+FR).")


if __name__ == "__main__":
    main()
